---
apiVersion: v1
kind: Namespace
metadata:
  name: flask-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-file-upload-app
  name: python-file-upload-app
  namespace: flask-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-file-upload-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-file-upload-app
    spec:
      containers:
      - name: python-file-upload-app
        image: quay.io/rh_ee_mrudraia/flask-file-upload:v7
        ports:
        - containerPort: 5000

        volumeMounts:
          - name: image-file-system
            mountPath: /uploads
            

      volumes:
      - name: image-file-system
        persistentVolumeClaim:
          claimName: image-file-system
        

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: flask-ns
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: python-file-upload-app

# Persistent Volume for data persistence
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-file-system
  namespace: flask-ns
  labels:
    app: python-file-upload-app
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi